use_frameworks!

install! "cocoapods", :share_schemes_for_development_pods => false

pod "Webtrekk", :path => ".."

abstract_target "iOS" do
	platform :ios, "8.0"

	target "Example" do
      target "ModuleTest" do
 		target "TestsOld" do
            target "Tests" do
                inherit! :search_paths
                pod 'Quick', '~> 0.8'
                pod 'Nimble', '~> 3.0'
                pod 'FBSnapshotTestCase'
                pod 'Nimble-Snapshots'
                pod 'OHHTTPStubs'
                pod 'OHHTTPStubs/Swift'
                end
            end
		end
	end
end

post_install do |installer|

	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
			config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
			config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
			config.build_settings['SWIFT_VERSION'] = '2.3'
		end
	end
end


#abstract_target "watchOS" do
#	platform :watchos, "2.0"
#
#	target "WatchKit Extension"
#end
